{{- if and .Values.hooks.enabled .Values.hooks.preUpgrade.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "reportportal.fullname" . }}-pre-upgrade-cleanup
  labels:
    {{ include "labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.migrations.podLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        component: {{ include "reportportal.fullname" . }}-pre-upgrade-cleanup
      annotations:
        {{- range $key, $value := .Values.migrations.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "reportportal.serviceAccountName" . }}
      restartPolicy: OnFailure
      containers:
      - name: delete-job
        image: "{{ include "reportportal.image" (dict "Values" .Values "service" "kubectl") }}"
        {{- if .Values.global.securityContext }}
        securityContext:
          {{ toYaml .Values.global.securityContext | nindent 10 }}
        {{- end }}
        command:
        - /bin/sh
        - -c
        - |
          kubectl delete job {{ include "reportportal.fullname" . }}-migrations --ignore-not-found=true
        resources:
          requests:
            cpu: {{ .Values.hooks.resources.requests.cpu }}
            memory: {{ .Values.hooks.resources.requests.memory }}
          limits:
            cpu: {{ .Values.hooks.resources.limits.cpu }}
            memory: {{ .Values.hooks.resources.limits.memory }}
{{- end }}
